package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"path/filepath"
	"time"

	"github.com/seanrmurphy/tgle/dbqueries"
)

func generateJSONReport(c *Config) error {
	lg.Sugar().Info("Generating JSON report\n")

	db, err := sql.Open("sqlite3", filepath.Join(c.TgleStateDirectory, dbFilename))
	if err != nil {
		lg.Sugar().Errorf("error opening database: %v", err)
		return err
	}

	queries := dbqueries.New(db)

	recentLinks, err := queries.GetLinksWithSender(context.TODO())
	if err != nil {
		lg.Sugar().Error("error getting links: %v", err)
		return err
	}

	jsonOutput, err := json.Marshal(recentLinks)

	fmt.Printf("%s\n", jsonOutput)

	return nil
}

func generateMarkdownReport(c *Config) error {
	lg.Sugar().Info("Generating markdown report\n")

	db, err := sql.Open("sqlite3", filepath.Join(c.TgleStateDirectory, dbFilename))
	if err != nil {
		lg.Sugar().Error("error opening database: %v", err)
		return err
	}

	queries := dbqueries.New(db)

	recentLinks, err := queries.GetLinksWithSender(context.TODO())
	if err != nil {
		lg.Sugar().Error("error getting links: %v", err)
		return err
	}

	fmt.Printf("\n# Link report generated by tgle on %v - recent links\n\n", time.Now().Format(time.RFC3339))
	for _, l := range recentLinks {
		sentAt := time.Unix(l.SentAt, 0).Format(time.RFC3339)
		fmt.Printf("- [%v](%v) - Sent by %v on %v\n", l.PageTitle.String, l.Url, l.SentBy.String, sentAt)
	}

	return nil
}
