package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"path/filepath"
	"time"

	"github.com/seanrmurphy/tgle/dbqueries"
)

func generateJSONReport(c *Config) error {
	log.Printf("Generating JSON report\n")

	db, err := sql.Open("sqlite3", filepath.Join(c.TgleStateDirectory, dbFilename))
	if err != nil {
		log.Printf("error opening database: %v", err)
		return err
	}

	queries := dbqueries.New(db)

	recentLinks, err := queries.GetLinks(context.TODO())
	if err != nil {
		log.Printf("error getting links: %v", err)
		return err
	}

	jsonOutput, err := json.Marshal(recentLinks)

	fmt.Printf("%s\n", jsonOutput)

	return nil
}

func generateMarkdownReport(c *Config) error {
	log.Printf("Generating markdown report\n")

	db, err := sql.Open("sqlite3", filepath.Join(c.TgleStateDirectory, dbFilename))
	if err != nil {
		log.Printf("error opening database: %v", err)
		return err
	}

	queries := dbqueries.New(db)

	recentLinks, err := queries.GetLinks(context.TODO())
	if err != nil {
		log.Printf("error getting links: %v", err)
		return err
	}

	fmt.Printf("\n# Link report generated by tgle on %v - recent links\n\n", time.Now().Format(time.RFC3339))
	for _, l := range recentLinks {
		fmt.Printf("- [%v](%v)\n", l.PageTitle.String, l.Url)
	}

	return nil
}
