// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbqueries

import (
	"database/sql"
)

type Link struct {
	ID        int64
	Url       string
	Site      sql.NullString
	PageTitle sql.NullString
	Tags      sql.NullString
}

type Message struct {
	ID      int64
	SentAt  int64
	SentBy  sql.NullString
	Message string
}

type TgleSync struct {
	ID            int64
	SyncTime      sql.NullInt64
	MessagesAdded sql.NullInt64
	LinksAdded    sql.NullInt64
}

type UserChat struct {
	ID         int64
	LastUpdate sql.NullInt64
}
